### ISSUE TITLE
求更新教程-来自一个小白

### ISSUE THREAD

**Issue by Kevin0521-AI2** [LiuChangFreeman/OneIndex-Serverless#30]
作者大大您好！一个来自2020/4/1的小白表示，现在才看到您的教程，然鹅，阿里云函数计算部分已经与您当时有很大出入，如果您能更新一下教程，感激不尽！
祝好！

**Comment by Kevin0521-AI2** [comment]
> 作者大大您好！一个来自2020/4/1的小白表示，现在才看到您的教程，然鹅，阿里云函数计算部分已经与您当时有很大出入，如果您能更新一下教程，感激不尽！
> 祝好！

经过摸索，已经配置好啦！感谢作者大大详尽的教程！不知是否有时间升级推出在线播放功能？如可，感激不尽！

**Comment by tinyhugh** [comment]
求问，最后登陆onedrive账号的时候，回调时总是下载一个authorized.html怎么解决？
