### ISSUE TITLE
希望添加返回上一层目录按钮

### ISSUE THREAD

**Issue by feilongproject** [LiuChangFreeman/OneIndex-Serverless#8]
就像这样
![](https://i.loli.net/2019/09/19/a58HrvZdEiQXkFy.jpg)

**Comment by LiuChangFreeman** [comment]
您可以点击任意一个超链接返回到上级目录
![TIM截图20191008090410](https://user-images.githubusercontent.com/20047907/66359684-a4cb2680-e9aa-11e9-9a05-94752b51fa97.png)
